apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: myargo
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/apache/airflow'
    chart: 'chart'
    targetRevision: 'main'
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
