executor: "KubernetesExecutor"

airflow:
  config:
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "2.10.0"
postgresql:
  enabled: false 
postgresql-ha:
  enabled: true 
  postgresql:
    password: "postgres"
    repmgrPassword: "postgres"
  pgpool:
    enabled: true
