apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: airflow
  namespace: myargo

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 20.0.0
    helm:
      parameters:
        - name: "executor"
          value: "KubernetesExecutor"
      values: |
        executor: "KubernetesExecutor"
        config:
          AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres123@postgresql-ha-pgpool.myargo.svc.cluster.local:5432/postgres
        postgresql:
          enabled: false
        data:
        metadataConnection:
          user: postgres
          pass: postgres123
          protocol: postgresql
          host: postgresql-ha-pgpool.myargo.svc.cluster.local
          port: 5432
          db: postgres
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
        useStandardNaming: true
        redis:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true