apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: airflow
  namespace: myargo

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 18.0.0
    helm:
      values: |
        airflow:
          executor: KubernetesExecutor
          config:
            AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
        postgresql:
          enabled: false
        externalDatabase:
          type: postgresql
          host: postgres-ha-postgresql-ha-pgpool.postgres.svc.cluster.local
          port: 5432
          database: postgres 
          user: postgres 
          passwordSecret: postgres123
          existingSecret: secret
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
        useStandardNaming: true
        redis:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true