apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: myargo
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql-ha
    targetRevision: 14.3.4
    helm:
      values: |
        global:
          postgresql:
            username: "postgres"
            password: "postgres123"
            database: "postgres"
            repmgrUsername: "repmgr"
            repmgrPassword: "repmgr123"
            repmgrDatabase: "repmgr"
            debug: true
            persistence:
              enabled: true
              size: 1Gi
              mountPath: "/bitnami/postgresql"
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
