apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: myargo
spec:
  project: default
  
  source:
    repoUrl: https://charts.bitnami.com/bitnami
    chart: postgresql-ha
    targetRevision: 14.3.4
    helm:
      valueFiles:
        - ./postgresql-ha/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
