apiVersion: batch/v1
kind: Job
metadata:
  name: create-repmgr-db
  namespace: postgres
spec:
  template:
    spec:
      containers:
      - name: create-repmgr-db
        image: bitnami/postgresql-repmgr:latest
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-ha-postgresql
              key: postgres-password
        command: ["psql"]
        args: ["-h", "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.postgres.svc.cluster.local", "-U", "postgres", "-c", "CREATE DATABASE repmgr; GRANT ALL PRIVILEGES ON DATABASE repmgr TO repmgr;"]
      restartPolicy: OnFailure
