airflow:

  executor: KubernetesExecutor
      
  config:
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
  
  database:
    secretName: secret

  # External PostgreSQL DB settings
  postgresql:
    enabled: false  # Disable built-in PostgreSQL
  externalDatabase:
    type: postgresql
    host: postgres-ha-postgresql-ha-pgpool.postgres.svc.cluster.local
    port: 5432
    database: postgres 
    user: postgres 
    passwordSecret: postgres123
    existingSecret: true