# # apiVersion: argoproj.io/v1alpha1
# kind: Application


# metadata:
#   name: airflow
#   namespace: myargo # Change this if your Argo CD is in a different namespace


# spec:
#   project: default

#   source:
#     repoURL: oci://registry-1.docker.io/bitnamicharts/airflow
#     chart: airflow
#     targetRevision: 1.8.0  # Specify the version of Airflow chart (update as necessary)
    
#     # Optional: You can add specific Helm values here
#     helm:
#       values: |
#         airflow:
#           executor: CeleryExecutor
#           config:
#             AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
#         workers:
#           replicas: 3
          
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: airflow  # Namespace where you want to install Airflow (make sure it exists)

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true  # Automatically create the namespace if it does not exist

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: airflow
  namespace: myargo

spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/airflow
    chart: airflow
    targetRevision: 1.8.0

    helm:
      values: |
        airflow:
          executor: KubernetesExecutor
          config:
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
        workers:
          replicas: 3
          
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow  # The namespace where Airflow is installed

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically create namespace if it doesn't exist
