apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: myargo
type: Opaque
data:
  POSTGRES_USER: "cG9zdGdyZXNfdXNlcg=="
  POSTGRES_PASSWORD: "cG9zdGdyZXNfcGFzc3dvcmQ="
  POSTGRES_DB: "cG9zdGdyZXNfZGI="
