name: Lint YAML and Kubernetes Manifests

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Install kube-linter
        run: |
          curl -Lo kube-linter.tar.gz https://github.com/stackrox/kube-linter/releases/download/v0.2.6/kube-linter-linux.tar.gz
          tar -xvf kube-linter.tar.gz -C /usr/local/bin/ kube-linter

      - name: Lint Kubernetes manifests
        run: |
          kube-linter lint . --format sarif || true
